
#ifndef WEBPREFS_H
#define WEBPREFS_H
#define WEBPREFS_VERSION "0.8"
#include <ESPAsyncWebServer.h>
#if defined(ESP8266)
	#include <ESPAsyncTCP.h>
  #include <Updater.h>
#elif defined(ESP32)
	#include <AsyncTCP.h>
  #include <Update.h>
#endif

#include <vector>
#include "page.h"  // --- do not modify -- page.h is auto-generated by pre-build script minify.py ---
#include "serlog.h"

class WebPrefs {
  public:
    enum {
        STRING = 1,
        FLOAT,
        UINT16,
        UINT32,
        INT16,
        INT32,
        PASSWORD,
        CHECKBOX
    };

    struct input_field {
        uint8_t type;
        const char *name;
        const char *value;        
        uint16_t size;
        uint16_t offset;      // maybe increase to uint32_t
        int32_t min;
        int32_t max;
        void (*callback)();      
    };

    void begin(int port, void *prefs, 
      const std::vector<input_field> &_fields, 
      std::function<void()> cbDone = nullptr, 
      std::function<void(int params)> cbSave = nullptr, 
      std::function<void()> cbBeforeResponse = nullptr);
    void end();
    void start();
    void stop();
    void setDefaults();
    void debugPrintConfig();
    void onDataRequest(AsyncWebServerRequest *request);
    void onDataReceive(AsyncWebServerRequest *request);
    void onIndex(AsyncWebServerRequest *request);
    void onDataUpload(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final);
    void onDone(AsyncWebServerRequest *request);
    void notFound(AsyncWebServerRequest *request);
    void setAuthentication(const bool auth, const char *_user = "admin", const char *_password = "");
    String url_encode(const String &str) const;
    String url_decode(const String &str, bool decode_plus = false) const;
    unsigned long getIdleTime() const;
    void resetIdleTime();


  private:
    AsyncWebServer *server;
    bool checkCredentials(AsyncWebServerRequest *request);
    bool setValue(const String &value, const String &name) const;
    void setValue(const String &value, int index) const;
    String getValue(int index) const;
    
    struct ChunkState {
        size_t index = 0;
        size_t offset = 0;
    };

    std::vector<input_field> fields;
    const char *user;
    const char *password;
    void *prefs;
    bool ap_mode;
    bool is_auth;
    bool is_running;
    unsigned long last_activity = 0;
    mutable int value_index;
    std::function<void()> done;
    std::function<void(int params)> save;
    std::function<void()> beforeResponse;
    static size_t chunkedCallback(uint8_t* buffer, size_t maxLen, ChunkState* state);
};

#endif // WEBPREFS_H